### ISSUE TITLE
Feature Request : Keyboard Shortcut

### ISSUE THREAD

**Issue by ghost** [kra-mo/quick-touchpad-toggle#2]
Hi, 

Thanks again for making this extension.

Is there a way to map it to a keyboard shortcut?

cheers

**Comment by kra-mo** [comment]
Hi, thanks for the interest.

Currently, I think a keyboard shortcut is out of the scope of the project. For it to work as expected, I would have to make the indicator update on outside changes to the setting and probably include an extension settings dialog too. 

However, if you would like to use a shortcut on your own, you could do it by using a shell script like this one:
```bash
value=$(gsettings get org.gnome.desktop.peripherals.touchpad disable-while-typing) && if $value = true; then value=false; else value=true; fi && gsettings set org.gnome.desktop.peripherals.touchpad disable-while-typing $value
```
Save it to a file and make it executable. Then copy it to either `~/.local/bin/` for a local, or `/usr/bin/` for a system-wide installation.

After, you can create a shortcut for it in GNOME Settings. Go to Keyboard > View and Customize Shortcuts > Custom Shortcuts. Create a new one, give it a name, assign a shortcut, and set the command as the file name you have chosen for the script.

I hope I was able to help.
Closing this with wontfix, but might reopen if there is more interest.

**Comment by ghost** [comment]
Thank you, that's just the job.
