### ISSUE TITLE
Doesn't work on Razer Blade 15” Advanced (2018)

### ISSUE THREAD

**Issue by libook** [kra-mo/quick-touchpad-toggle#4]
OS: Manjaro
DE: gnome-shell 43.1

Thank you for making this extension.
I can install it. And it has correctly shown on the panel with no error. I can click it to switch status. But I can still move cursor with touch pad after I switched it off. The switch in Gnome Setting works well.

**Comment by kra-mo** [comment]
Hi,
This extension is meant for toggling the "Disable While Typing" setting found in GNOME Tweaks, not the entire touchpad. However, I've considered expanding this extension with more settings and will update this issue if I do so.
