### ISSUE TITLE
Touchpad toggle not working 

### ISSUE THREAD

**Issue by OriAlpha** [kra-mo/quick-touchpad-toggle#6]
Extension is awesome, 
recently i updated from ubuntu 20 to 22, after update the extension doesnt work, even uninstalling didnt work. 
Any ideas to debug!!

**Comment by kra-mo** [comment]
Hi, thanks.

Does the extension load?
If so, what behaves unexpectedly?
If not, what error message are you getting?

**Comment by OriAlpha** [comment]
Extension loads with any errors, when it’s installed it gives an icon to disable touchpad, when i click it touchpad still works. It doesn't disable!

**Comment by kra-mo** [comment]
When the button is active, it means that the touchpad is enabled. It will be disabled when the button is inactive. I hope this fixes your issue.

**Comment by OriAlpha** [comment]
But for me, it stay on always, both cases.

**Comment by kra-mo** [comment]
I am not sure why that would be the case.
Can you please provide the output of `gsettings get org.gnome.desktop.peripherals.touchpad disable-while-typing` before and after toggling the button?

**Comment by OriAlpha** [comment]
both cases its same output 

```
user:~$ gsettings get org.gnome.desktop.peripherals.touchpad disable-while-typing
true
user:~$ gsettings get org.gnome.desktop.peripherals.touchpad disable-while-typing
true
```

**Comment by kra-mo** [comment]
In that case, I am not sure what the issue could be. I would try disabling all other extensions and see if the problem still persists.
Could you also show me how the button in the quick settings menu looks before and after toggling it?

**Comment by OriAlpha** [comment]
![Screenshot from 2023-04-03 09-06-57](https://user-images.githubusercontent.com/41699212/229436232-5b058ad4-38be-4fdf-b21e-5ca9442759ca.png)
![Screenshot from 2023-04-03 09-07-22](https://user-images.githubusercontent.com/41699212/229436305-70cf8fae-97aa-4ad7-8523-fb9c4edf77bf.png)

so far these are pictures

**Comment by kra-mo** [comment]
Hi!
I finally had the time to try out the extension in both a fresh Ubuntu 22.04 and an Ubuntu 22.10 VM, however I was not able to reproduce the issue, so it is probably not related to the extension.

You could try and install and older release of the extension and see if it fixes the issue.

PS, as for uninstalling, delete `~/.local/share/gnome-shell/extensions/quick-touchpad-toggle@kramo.hu` and restart GNOME.
