### ISSUE TITLE
Latest gnome shell internal changes break extension code on gnome 4

### ISSUE THREAD

**Issue by ionutbortis** [kra-mo/quick-touchpad-toggle#8]
Hello,

While updating my extension to 45 I also installed this extension in order to test along with the Quick Settings toggles.

It seems that this [commit](https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/93b89ce0c5c64a0770ea51120dc2326c1b3863ab?view=parallel) is breaking your extension's code because they removed the `_addItems` method:

```
(gnome-shell:5893): Gjs-WARNING **: 13:24:58.978: JS ERROR: Extension quick-touchpad-toggle@kramo.hu: TypeError: (intermediate value).statusArea.quickSettings._addItems is not a function
_init@file:///home/ionut/.local/share/gnome-shell/extensions/quick-touchpad-toggle@kramo.hu/extension.js:81:40
SystemIndicator@resource:///org/gnome/shell/ui/quickSettings.js:833:1
FeatureIndicator@file:///home/ionut/.local/share/gnome-shell/extensions/quick-touchpad-toggle@kramo.hu/extension.js:61:1
enable@file:///home/ionut/.local/share/gnome-shell/extensions/quick-touchpad-toggle@kramo.hu/extension.js:92:27
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:250:38
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:454:32
async*_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:724:24
async*_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:730:48
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:765:20
async*init@resource:///org/gnome/shell/ui/extensionSystem.js:69:14
_initializeUI@resource:///org/gnome/shell/ui/main.js:290:22
start@resource:///org/gnome/shell/ui/main.js:163:11
@resource:///org/gnome/shell/ui/init.js:11:47
@resource:///org/gnome/shell/ui/init.js:21:20
```

The above mentioned commit is not yet released, but it is merged to their main branch. I observed this because I've built the latest code inside a vm in order to have the [latest changes](https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/2894) related to Quick Settings.

They recommend now for extensions to use the new `addExternalIndicator` method from `panel.js`.

I gues your code from `extension.js`:
```
...
panel.statusArea.quickSettings._indicators.add_child(this);
panel.statusArea.quickSettings._addItems(this.quickSettingsItems);

for (const item of this.quickSettingsItems) {
    panel.statusArea.quickSettings.menu._grid.set_child_below_sibling(item, panel.statusArea.quickSettings._backgroundApps.quickSettingsItems[0]);
}
...
```

would change to something like this:
```
...
panel.statusArea.quickSettings.addExternalIndicator(this);
...
```

This new method also takes care of adding the toggle before the background apps section.

Just Perfection mentioned on the matrix channel that we should test the new ego submissions on an official build (proper release candidate) of gnome shell. So I guess that means we should wait for gnome os or fedora rawhide to push the latest 45 build.

HTH,
Ionut

**Comment by kra-mo** [comment]
Yeah, I've seen that. I'll port to it as soon as Fedora ships the newer build so I can test it.

**Comment by kra-mo** [comment]
I couldn't wait lol

**Comment by ionutbortis** [comment]
Well, good news and bad news.

The good news is that v9 works on the latest Gnome OS Nightly. The toggle is added properly to QuickSettings and it seems to change the dconf value.

The bad news is that I get this error in journalctl (`journalctl -fo cat`) when using the toggle:
```
Object .Gjs_quick-touchpad-toggle_kramo_hu_extension_FeatureToggle (0x564dbbb3b420), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
== Stack trace for context 0x564db6882ac0 ==
#0   7fff41387c40 b   resource:///org/gnome/gjs/modules/core/_common.js:37 (6063b9c510 @ 70)
#1   564db6948d48 i   file:///home/ionut/.local/share/gnome-shell/extensions/quick-touchpad-toggle@kramo.hu/extension.js:54 (6063ba41a0 @ 100)
#2   564db6948cc8 i   file:///home/ionut/.local/share/gnome-shell/extensions/quick-touchpad-toggle@kramo.hu/extension.js:44 (6063ba4150 @ 12)
#3   564db6948c38 i   resource:///org/gnome/shell/ui/init.js:21 (6063b70ba0 @ 48)
```

**Comment by ionutbortis** [comment]
The previous mentioned errors don't occur after a fresh login, but if you run this you get them afterwards when using the toggle:

```
gnome-extensions disable quick-touchpad-toggle@kramo.hu
gnome-extensions enable quick-touchpad-toggle@kramo.hu
```

I don't know what's causing them. The same thing happens if you disable/enable it from Extensions or Extension Manager.

**Comment by kra-mo** [comment]
Well, I copied the destroy and activate methods from gjs.guide so unless there's an issue with that, this might be an upstream bug?

**Comment by ionutbortis** [comment]
I  have no idea... My extension doesn't put out that error when I'm using the toggle. Settings Center's toggle puts out an error, but a different kind:

```
clutter_actor_insert_child_below: assertion 'child->priv->parent == NULL' failed
```

Just logged in to my Fedora Rawhide with a local build of gnome-shell from 2 days ago (their main branch), got your extension's update, relogin, first clicks on the toggle, no errors, after disable/enable, same errors,

Your code also looked fine to me, not sure what could cause the error. Maybe the guys from the matrix channel could figure out why that happens.
